spring:
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5432/news-service-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.ondra.services@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          audiences: ${OAUTH2_AUDIENCE}
  threads:
    virtual:
      enabled: true

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini