spring:
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5432/news-service-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          audiences: ${OAUTH2_AUDIENCE}
  threads:
    virtual:
      enabled: true

external-api:
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o-mini